# Generated by Django 4.2 on 2024-08-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('L', 'Lagartija'), ('F', 'Fuego'), ('P', 'Planta'), ('T', 'Tierra'), ('A', 'Agua')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='region',
            field=models.CharField(choices=[('Alola', 'Alola'), ('Paldea', 'Paldea'), ('Kalos', 'Kalos'), ('Galar', 'Galar'), ('Johto', 'Johto'), ('Kanto', 'Kanto'), ('Sinnoh', 'Sinnoh'), ('Unova', 'Unova'), ('Hoenn', 'Hoenn')], max_length=30),
        ),
    ]
